version: '3.9'

services:
  nidjat-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: nidjat_app
    ports:
      - '${DJANGO_PORT}:8000'
    command: 'sh /entrypoint.sh'
    env_file:
      - ../.env
    depends_on:
      - nidjat-db
    volumes:
      - ..:/app/