# Generated by Django 5.0.4 on 2024-04-24 14:16

import django.contrib.auth.validators
from django.db import (
    migrations,
    models,
)

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Cashier', 'Cashier'), ('Moderator', 'Moderator'), ('Admin', 'Admin')], default='Customer', max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Телеграм'),
        ),
    ]
