# Generated by Django 5.0.6 on 2024-06-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
