# Generated by Django 5.0.6 on 2025-04-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Клиент'), ('Cashier', 'Кассир'), ('Moderator', 'Модератор'), ('Admin', 'Администратор'), ('Depositor', 'Инвестор')], default='Customer', max_length=50, verbose_name='Роль'),
        ),
    ]
