# Generated by Django 5.0.6 on 2024-06-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount_in_goods', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Сумма в товаре')),
                ('amount_in_defects', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Сумма в браке')),
            ],
            options={
                'verbose_name': 'Финансы',
                'verbose_name_plural': 'Финансы',
            },
        ),
    ]
