# Generated by Django 5.0.6 on 2024-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_finances_amount_in_defects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finances',
            name='debt_for_goods_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма долга за товар'),
        ),
        migrations.AddField(
            model_name='finances',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма доходов'),
        ),
    ]
