# Generated by Django 5.0.6 on 2024-07-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_finances_debt_for_goods_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Кеш в обороте',
                'verbose_name_plural': 'Кеш в обороте',
            },
        ),
    ]
