# Generated by Django 5.0.6 on 2024-06-09 19:11

import core.apps.receipts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to=core.apps.receipts.models.receipt_filename),
        ),
    ]
