# Generated by Django 5.0.6 on 2024-05-14 16:22

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Баланс'),
        ),
    ]
