# Generated by Django 5.0.6 on 2024-05-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_client_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='client',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='client_balance',
            new_name='customer_balance',
        ),
    ]
